### ISSUE TITLE
Line highlight color makes it near impossible to read text

### ISSUE THREAD

**Issue by josh-nz** [catppuccin/bat#12]
A line highlight colour was adjusted in #2 with commit https://github.com/catppuccin/bat/commit/ba4d16880d63e656acced2b7d4e034e4a93f74b1

This set the `lineHighlight` to `#585b70` in the Mocha theme, for example.

The current `lineHightlight` in this theme is `#cdd6f412` which makes the text nearly impossible to read. 

A similar issue affects the other Catppuccin `bat` themes here.

I'm not sure why this this colour was changed, but perhaps revert it back?

<img width="1314" alt="Screen Shot 2024-04-04 at 19 45 33" src="https://github.com/catppuccin/bat/assets/414204/8411ff50-8840-40f8-b141-17e3c9cf1269">

**Comment by josh-nz** [comment]
Ok, the older `lineHighlight` has readability issues with commented lines, so perhaps a new highlight color needs to be found:

<img width="629" alt="Screen Shot 2024-04-04 at 19 51 57" src="https://github.com/catppuccin/bat/assets/414204/85861a8b-4567-4b62-9565-e617ff5276ec">

**Comment by lpnh** [comment]
I was about to report the same issue. Changing to `Surface0` and keeping the same alpha value solved it for me. See: https://github.com/lpnh/dotfiles/commit/0173de7dcacabc6d94e828d58c281dc10aec7593
