### ISSUE TITLE
Incorrect config file location

### ISSUE THREAD

**Issue by asilvadesigns** [catppuccin/bat#25]
The README.md states that the bat config file is usually located at `~/.config/bat/config`.

Perhaps a line can be added under stating "additional details here: https://github.com/sharkdp/bat?tab=readme-ov-file#configuration-file" linking to the official documentation for config files. In my case it was ~/.config/bat/bat.conf.

I can raise PR if the maintainers think this is a useful addition.

**Comment by uncenter** [comment]
It already says:

> located at `bat --config-file` (usually `~/.config/bat/config`):

Did `bat --config-file` give you the wrong path? I think linking that would be welcome but the command is already there.

**Comment by sgoudham** [comment]
Hey 👋 

As @uncenter mentions above, we do have `bat --config-file` mentioned in the README. That being said, happy to accept a PR that adds a link to upstream docs.

**Comment by asilvadesigns** [comment]
Thank you!!
