### ISSUE TITLE
one of the color pallet is out of spec

### ISSUE THREAD

**Issue by dhruvinsh** [catppuccin/bat#28]
color in [themes/Catppuccin Mocha.tmTheme](https://github.com/catppuccin/bat/blob/d3feec47b16a8e99eabb34cdfbaa115541d374fc/themes/Catppuccin%20Mocha.tmTheme#L36) doesn't belong to catppuccin color specs.

```
 <key>findHighlight</key> 
 <string>#3e5767</string> 
```
update: originally I created this issue with `#313244` but that was mistake, I intend to create for `#3e5767` color.

**Comment by uncenter** [comment]
Do you mean that `#313244` isn't a Catppuccin color? It is Surface 0 in Mocha (see https://catppuccin.com/palette). Or do you mean that the color isn't following the style guide?

**Comment by dhruvinsh** [comment]
apologies, I have pasted a wrong code block, correct one is, I will update the above issue,

https://github.com/catppuccin/bat/blob/d3feec47b16a8e99eabb34cdfbaa115541d374fc/themes/Catppuccin%20Mocha.tmTheme#L36-L37

**Comment by uncenter** [comment]
That color is a mix of Base and Sky: https://github.com/catppuccin/vscode/blob/54316f9afc31c3b5070a242cd3ca47d66ab0e9ac/packages/catppuccin-vsc/src/theme/uiColors.ts#L136.

**Comment by dhruvinsh** [comment]
Thank you for confirming.
