### ISSUE TITLE
improve the syntax highlighting when using bat as a manpager on a catppuccin theme

### ISSUE THREAD

**Issue by Ioulan** [catppuccin/bat#3]
Not an issue, just a suggestion for context and comparison,
Here's a screenshot of the manpages using vs Monokai Theme
![Screenshot from 2022-12-12 18-34-06](https://user-images.githubusercontent.com/114978689/207054465-e75f9123-3c8c-4f34-8f08-736adae243d2.png)
As you can see above on the left side using Catppuccin most of the colors are white others doesn't get higlighted

**Comment by mac1202** [comment]
+1 for your suggestion.

Just a question, do you know how to get a nice status line in man page like in your screenshot. On my PC whenever colorscheme or terminal I use I get this ugly blue status line in man page.

![Screenshot_20230315_170449](https://user-images.githubusercontent.com/5730439/225370223-872134cd-1a8e-460e-87fa-5dbef047bd6d.png)

**Comment by blurgyy** [comment]
Hi @mac1202, If your pager is `less`, the highlight on the status line can be controlled by `LESS_TERMCAP_*` variables.  More info here: <https://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables>

**Comment by mac1202** [comment]
> Hi @mac1202, If your pager is `less`, the highlight on the status line can be controlled by `LESS_TERMCAP_*` variables. More info here: https://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables

thanks for your answer.

**Comment by drod3763** [comment]
Definitely would like to see some flag highlighting for stuff like manpages here. Great themes otherwise.

**Comment by FTQuin** [comment]
+1 for this! It would be great

**Comment by nekowinston** [comment]
Whoever wants to pick this up would have to add https://github.com/sharkdp/bat/blob/master/assets/syntaxes/02_Extra/Manpage.sublime-syntax scopes to the build script to merge with the generated theme.
