### ISSUE TITLE
JSON Keys Are Green

### ISSUE THREAD

**Issue by eitamal** [catppuccin/bat#30]
Hey there,

So, it looks like JSON keys are highlighted **green**:

![JSON keys are shown using the green accent](https://github.com/user-attachments/assets/8429e8f4-4f7d-4afb-a868-d9643ab7ab24)
> *— using Windows Terminal v1.21.231.0, Ubuntu 22.04.05 (WSL), and bat v0.24.0 (Macchiato flavour)*

When in the theme file, it seems it should be **blue**:

![JSON property names set to blue](https://github.com/user-attachments/assets/55ab4bd9-d83f-4070-9d87-bc0cd11a5296)
> *— the colour is macchiato's blue*

I managed to fix it by adding the following two sections, which I based on the [sublime theme](https://github.com/catppuccin/sublime-text) (**blue** keys and **overlay2** quotes):

```xml
      <dict>
        <key>name</key>
        <string>JSON Keys</string>
        <key>scope</key>
        <string>source.json meta.mapping.key string</string>
        <key>settings</key>
        <dict>
          <key>foreground</key>
          <string>#8aadf4</string>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>JSON key surrounding quotes</string>
        <key>scope</key>
        <string>source.json meta.mapping.key punctuation.definition.string.begin, source.json meta.mapping.key punctuation.definition.string.end</string>
        <key>settings</key>
        <dict>
          <key>foreground</key>
          <string>#939ab7</string>
        </dict>
      </dict>
      <dict>
```

Which now looks much better:

![Fixed now with blue JSON keys](https://github.com/user-attachments/assets/c5b9eab0-90ca-4f21-a890-39004e6fb0b9)

I'm happy to open a PR that adds these fixes to a `json.js` syntax file if you'd like.

But digging a bit deeper into it, I realised that the section that is supposed to deal with it originally ([line 519](https://github.com/catppuccin/bat/blob/d2bbee4f7e7d5bac63c054e4d8eca57954b31471/themes/Catppuccin%20Macchiato.tmTheme#L519)), doesn't seem to do anything for `JSON`, `INI`, `TOML`, and `YAML`. After some more digging around, I realised that `bat` and `vscode` use different syntax definition files — so highlighting that works for `vscode` isn't always going to work for `bat`. Which you probably already knew, so I figured I'm probably just wasting my time… 🙃 

Anyway, hopefully this is useful and thanks for maintaining this port! And let me know if you'd want that PR.

**Comment by chris4prez** [comment]
I came here to call out same issue and noticed bat is rendering JSON primarily in green.

Fedora 41, bat 0.24.0, catppuccin-mocha.

**Comment by sgoudham** [comment]
Thanks for investigating a bit more and finding a fix! @eitamal 

> I'm happy to open a PR that adds these fixes to a json.js syntax file if you'd like.

Please do! A new `json.ts` file in the [syntaxes directory](https://github.com/catppuccin/bat/tree/main/src/syntaxes) makes the most sense to me since it's not following VSCode.
